name: hbv-artic
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.0.0=pyhd8ed1ab_0
  - aiohttp=3.9.1=py310h2372a71_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - args=0.1.0=pyhd8ed1ab_1004
  - artic-porechop=0.3.2pre=py310h0dbaff4_5
  - artic-tools=0.3.1=h4f9544c_4
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - bcftools=1.17=h3cc50cf_1
  - biopython=1.83=py310h2372a71_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bwa=0.7.17=he4a0461_11
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.25.0=hd590300_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.2=pyhd8ed1ab_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - clint=0.5.1=py_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=py310hff52083_2
  - colormath=3.0.0=py_2
  - contourpy=1.2.0=py310hd41b1e2_0
  - cryptography=39.0.0=py310h65dfdc0_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - flatbuffers=2.0.8=hcb278e6_1
  - fonttools=4.47.2=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.4.1=py310h2372a71_0
  - future=0.18.3=pyhd8ed1ab_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h0b41bf4_3
  - google-auth=2.26.2=pyhca7485f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.47.1=h05bd8bd_7
  - grpcio=1.47.1=py310h5b20944_7
  - gsl=2.7=he838d99_0
  - h5py=3.8.0=nompi_py310h0311031_100
  - hdf5=1.12.2=nompi_h2386368_101
  - htslib=1.17=h6bc39ce_1
  - humanfriendly=10.0=py310hff52083_5
  - humanize=4.9.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - intervaltree=3.1.0=pyhd8ed1ab_1
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - k8=0.2.5=hdcf5f25_4
  - keras=2.10.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20220623.0=cxx17_h05df665_6
  - libaec=1.1.2=h59595ed_1
  - libblas=3.9.0=20_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgfortran-ng=13.2.0=h69a702a_3
  - libgfortran5=13.2.0=ha4646dd_3
  - libgomp=13.2.0=h807b86a_3
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.21.12=hfc55251_2
  - libsqlite=3.44.2=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=hd590300_5
  - longshot=0.4.5=hd175d40_2
  - lzstring=1.0.4=py_1001
  - mappy=2.26=py310h83093d7_1
  - markdown=3.5.2=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - matplotlib-base=3.8.2=py310h62c0568_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - medaka=1.11.3=py310h87e71ce_0
  - minimap2=2.26=he4a0461_2
  - multidict=6.0.4=py310h2372a71_1
  - multiqc=1.19=pyhdfd78af_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - muscle=3.8.1551=h7d875b9_6
  - nanopolish=0.14.0=h773013f_3
  - ncurses=6.4=h59595ed_2
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.3=py310hb13e2d6_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - ont-fast5-api=4.1.2=pyhdfd78af_0
  - ont_vbz_hdf_plugin=1.0.1=h3f9cce5_5
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.4=py310hcc13569_0
  - parasail-python=1.3.4=py310h6cc9453_0
  - perl=5.32.1=7_hd590300_perl5
  - pillow=9.2.0=py310h454ad03_3
  - pip=23.3.2=pyhd8ed1ab_0
  - pluggy=1.3.0=pyhd8ed1ab_0
  - progressbar33=2.4=py_0
  - protobuf=4.21.12=py310heca2aa9_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyabpoa=1.5.0=py310h83093d7_0
  - pyaml-env=1.1.0=pyhd8ed1ab_0
  - pyasn1=0.5.1=pyhd8ed1ab_0
  - pyasn1-modules=0.3.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyfaidx=0.6.0=pyh5e36f6f_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pysam=0.21.0=py310hff46b53_0
  - pysocks=1.7.1=py310hff52083_5
  - pyspoa=0.2.1=py310h2b6aa90_0
  - pytest=7.4.4=pyhd8ed1ab_0
  - python=3.10.8=h257c98d_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-edlib=1.3.9=py310h0dbaff4_4
  - python-flatbuffers=23.5.26=pyhd8ed1ab_0
  - python-tzdata=2023.4=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf=0.6.8=py310hff52083_1003
  - pyyaml=5.4.1=py310h5764c6d_4
  - re2=2022.06.01=h27087fc_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rich-click=1.7.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - samtools=1.18=hd87286a_0
  - scipy=1.11.4=py310hb13e2d6_0
  - simplejson=3.19.2=py310h2372a71_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - spectra=0.0.11=py_1
  - tar=1.34=hb2e2bae_1
  - tensorboard=2.10.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.1=py310h597c629_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.10.0=cpu_py310hd1aba9c_0
  - tensorflow-base=2.10.0=cpu_py310hc537a0e_0
  - tensorflow-estimator=2.10.0=cpu_py310had6d012_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2023d=h0c530f3_0
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.1.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py310h2372a71_0
  - wurlitzer=3.0.3=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.3=py310h2372a71_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  
prefix: /home/ubuntu/miniconda3/envs/hbv-artic